apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-api-demo
  labels:
    app: springboot-api-demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: springboot-api-demo
  template:
    metadata:
      labels:
        app: springboot-api-demo
    spec:
      imagePullSecrets:
      - name: ocirsecret
      containers:
      - name: springboot-api-demo
        image: REGIPADD/springboot-api-demo:latest
        ports:
        - containerPort: 8080
---
#service
apiVersion: v1
kind: Service
metadata:
  name: springboot-api-demo
spec:
  type: NodePort
  selector:
    app: springboot-api-demo
  ports:
  - name: springboot-api-demo
    protocol: TCP
    nodePort: 30500
    port: 8080
    targetPort: 8080
